### ISSUE TITLE
Not for Linux

### ISSUE THREAD

**Issue by giftedl** [WorriedArrow/WorriedUtils#1]
why no Linux :(

**Comment by WorriedArrow** [comment]
hmmm...
well...
i understand that you dont feel like paying micro$$$$oft,
but
i dont feel like implementing that...
not yet at least...
so...
IMPLEMENT IT YOURSELF!!!!!
jkjk i think everything should work on linux ill test it on vm rq

**Comment by WorriedArrow** [comment]
oh...
i have some implementations to work on! :D

**Comment by WorriedArrow** [comment]
give me a couple of mins
and ill fix it

**Comment by giftedl** [comment]
~ = home (C:\Users\(username) in windows)
/ = root (C:\ in windows)

if that helps you

**Comment by WorriedArrow** [comment]
ik lol ive used *nix before lol

but like when i say open C:\ it says can't find the file C:\...
heres error:

```
java.io.IOException: Failed to open C:\ . Error message: The system cannot find the file specified.

	at sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:82)
	at sun.awt.windows.WDesktopPeer.open(WDesktopPeer.java:56)
	at java.awt.Desktop.open(Desktop.java:269)
	at com.zeroedmc.worriedutils.commands.OpenCommand.executeCommand(OpenCommand.java:27)
	at com.zeroedmc.worriedutils.WorriedUtils.checkCmd(WorriedUtils.java:99)
	at com.zeroedmc.worriedutils.WorriedUtils.main(WorriedUtils.java:86)
```

**Comment by WorriedArrow** [comment]
just realized, there's a space there. Removing the space at the end of the string makes it work :D
